# Generated by Django 2.2.9 on 2020-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
