# Generated by Django 2.2.9 on 2020-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typename',
            name='name',
            field=models.CharField(choices=[('ISSUE', 'Issue'), ('FEATURE', 'Feature')], max_length=20),
        ),
    ]
