# Generated by Django 2.2.9 on 2020-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200126_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=20),
        ),
    ]
