# Generated by Django 2.2.9 on 2020-01-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200124_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default='Issue', on_delete=django.db.models.deletion.CASCADE, to='tickets.TypeName'),
        ),
    ]
